import Head from 'next/head'
import dynamic from 'next/dynamic'
import { Header } from '@/components/Header'
import { Canva } from '@/components/Canva'
import { ChartProvider } from '@/components/Echarts/ChartProvider'
import { StoreProvider } from '@/components/Echarts/StoreProvider'
import { UiProvider } from '@/provider/ui'
import { chartDefaultOption, TABLE_BAR_LINE_PIE } from '@/utils';

const DynamicComponentWithNoSSR = dynamic(
  () => import('../components/Hot'),
  {
    loading: () => <p></p>,
    ssr: false
  }
);

export default function Home() {
  
  return (
    <StoreProvider initialState={{ options: chartDefaultOption, initDataset: TABLE_BAR_LINE_PIE }}>
      <UiProvider>
        <ChartProvider>
          <Head>
            <title>Igraph</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
            <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
            <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
            <link rel="manifest" href="/site.webmanifest" />
            <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
            <meta name="msapplication-TileColor" content="#da532c" />
            <meta name="theme-color" content="#ffffff" />
          </Head>
          <main className="text-sm min-h-screen h-auto pl-6 pt-6 pr-6 flex flex-col bg-white text-slate-800 dark:bg-slate-800 dark:text-slate-100">
            <Header />
            <Canva />
            <div className="h-full min-h-[12rem] relative mb-4">
              <DynamicComponentWithNoSSR />
            </div>
          </main>
        </ChartProvider>
      </UiProvider>
    </StoreProvider>
  )
}
